WebAppAspNetMvcAutofac/Controllers/DisciplinesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using WebAppAspNetMvcAutofac.DataModel;
using WebAppAspNetMvcAutofac.Services.Abstractions;

namespace WebAppAspNetMvcAutofac.Controllers
{
    public class DisciplinesController : Controller
    {
        private IDisciplineService _disciplineService;
        public DisciplinesController(IDisciplineService disciplineService)
        {
            _disciplineService = disciplineService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var disciplines = _disciplineService.GetEntities();

            return View(disciplines);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var discipline = _disciplineService.Create();
            return View(discipline);
        }

        [HttpPost]
        public ActionResult Create(Discipline model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _disciplineService.Create(model);

            return RedirectPermanent("/Disciplines/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            _disciplineService.Delete(id);

            return RedirectPermanent("/Disciplines/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var discipline = _disciplineService.Edit(id);

            return View(discipline);
        }

        [HttpPost]
        public ActionResult Edit(Discipline model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _disciplineService.Edit(model);

            return RedirectPermanent("/Disciplines/Index");
        }

       
    }
}

WebAppAspNetMvcAutofac/Controllers/GroupsController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using WebAppAspNetMvcAutofac.DataModel;
using WebAppAspNetMvcAutofac.Services.Abstractions;

namespace WebAppAspNetMvcAutofac.Controllers
{
    public class GroupsController : Controller
    {
        private IGroupService _groupService;
        public GroupsController(IGroupService groupService)
        {
            _groupService = groupService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var groups = _groupService.GetEntities();

            return View(groups);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var group = _groupService.Create();
            return View(group);
        }

        [HttpPost]
        public ActionResult Create(Group model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _groupService.Create(model);

            return RedirectPermanent("/Groups/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            _groupService.Delete(id);

            return RedirectPermanent("/Groups/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var group = _groupService.Edit(id);

            return View(group);
        }

        [HttpPost]
        public ActionResult Edit(Group model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _groupService.Edit(model);

            return RedirectPermanent("/Groups/Index");
        }

       
    }
}

WebAppAspNetMvcAutofac/Controllers/LessonsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using WebAppAspNetMvcAutofac.DataModel;
using WebAppAspNetMvcAutofac.Services.Abstractions;

namespace WebAppAspNetMvcAutofac.Controllers
{
    public class LessonsController : Controller
    {
        private ILessonService _lessonService;
        public LessonsController(ILessonService lessonService)
        {
            _lessonService = lessonService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var lessons = _lessonService.GetEntities();

            return View(lessons);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var lesson = _lessonService.Create();
            return View(lesson);
        }

        [HttpPost]
        public ActionResult Create(Lesson model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _lessonService.Create(model);

            return RedirectPermanent("/Lessons/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            _lessonService.Delete(id);

            return RedirectPermanent("/Lessons/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var lesson = _lessonService.Edit(id);

            return View(lesson);
        }

        [HttpPost]
        public ActionResult Edit(Lesson model)
        {            
            if (!ModelState.IsValid)
                return View(model);

            _lessonService.Edit(model);

            return RedirectPermanent("/Lessons/Index");
        }
              
        

        [HttpGet]
        public ActionResult Detail(int id)
        {
            var lesson = _lessonService.Edit(id);

            return View(lesson);
        }
        
    }
}

WebAppAspNetMvcAutofac/Controllers/TeachersController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using WebAppAspNetMvcAutofac.DataModel;
using WebAppAspNetMvcAutofac.Services.Abstractions;

namespace WebAppAspNetMvcAutofac.Controllers
{
    public class TeachersController : Controller
    {
        private ITeacherService _teacherService;
        public TeachersController(ITeacherService teacherService)
        {
            _teacherService = teacherService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var teachers = _teacherService.GetEntities().ToList();

            return View(teachers);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var teacher = _teacherService.Create();
            return View(teacher);
        }

        [HttpPost]
        public ActionResult Create(Teacher model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _teacherService.Create(model);

            return RedirectPermanent("/Teachers/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            _teacherService.Delete(id);

            return RedirectPermanent("/Teachers/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var teacher = _teacherService.Edit(id);

            return View(teacher);
        }

        [HttpPost]
        public ActionResult Edit(Teacher model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _teacherService.Edit(model);

            return RedirectPermanent("/Teachers/Index");
        }

        [HttpGet]
        public ActionResult GetImage(int id)
        {
            var image = _teacherService.GetImage(id, Server);

            return File(new MemoryStream(image.Data), image.ContentType);
        }

    }
}

WebAppAspNetMvcAutofac/Views/Disciplines/Create.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Discipline

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Disciplines", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Disciplines", null, new { @class = "btn btn-danger" })

    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Disciplines/Edit.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Discipline

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Disciplines", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Disciplines", null, new { @class = "btn btn-danger" })
    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Disciplines/Index.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@using Common.Extensions
@model List<Discipline>

@{
    string controllerName = "Disciplines";
}
<br>
<h1><b>Дисциплины </b></h1>
<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Дисциплина
            </th>
            <th>
                Цели дисциплины
            </th>
            <th>
                Задачи дисциплины
            </th>
            <th>
                Разделы
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var discipline in Model)
        {
            <tr>
                <td>
                    @discipline.Name
                </td>
                <td>
                    @discipline.DisciplineGoal
                </td>
                <td>
                    @discipline.DisciplineObjectives
                </td>
                <td>
                    <pre>@discipline.MainSections</pre>
                </td>
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@discipline.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@discipline.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<div class="btn-create">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
</div>

WebAppAspNetMvcAutofac/Views/Groups/Create.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Group

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Groups", FormMethod.Post))
    {
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Groups", null, new { @class = "btn btn-danger" })
    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Groups/Edit.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Group

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Groups", FormMethod.Post))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Groups", null, new { @class = "btn btn-danger" })
    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Groups/Index.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@using Common.Extensions
@model List<Group>

@{
    string controllerName = "Groups";
}

<br>
<h1><b>Группы</b></h1>
<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Группа
            </th>
            <th>
                Количество студентов
            </th>
            
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model)
        {
            <tr>
                <td>
                    @group.GroupName
                </td>
                <td>
                    @group.NumberOfStudents
                </td>
                
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@group.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@group.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                    
                </td>
            </tr>
        }
    </tbody>
</table>
<br >
<div class="btn-create">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
</div>

WebAppAspNetMvcAutofac/Views/Lessons/Create.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Lesson

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()
        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Lessons", null, new { @class = "btn btn-danger" })
    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Lessons/Detail.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Lesson


<table class="table align-middle " style="text-align:center",>
    <tbody>
        <tr>

            <td>
                <br />
                <h1><u>@Model.Discipline.Name</u></h1>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>Аннотация</h3>
            </td>
        </tr>
    </tbody>
</table>

<div class="row">
    <div class="accordion ">
        <div class="accordion-item" style="background-color: #ffc107;">
            <h2 class="accordion-header" id="one">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse" aria-expanded="false" aria-controls="flush-collapse">
                    Цель дисциплины
                </button>
            </h2>
            <div id="flush-collapse" class="accordion-collapse collapse" aria-labelledby="one">
                <div class="accordion-body">
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineGoal</pre></span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="accordion ">
        <div class="accordion-item" style="background-color: #ffc107;">
            <h2 class="accordion-header" id="two">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse2" aria-expanded="false" aria-controls="flush-collapse2">
                    Задачи дисциплины
                </button>
            </h2>
            <div id="flush-collapse2" class="accordion-collapse collapse" aria-labelledby="two">
                <div class="accordion-body">
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineObjectives</pre></span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="accordion ">
        <div class="accordion-item" style="background-color: #ffc107;">
            <h2 class="accordion-header" id="three">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse3" aria-expanded="false" aria-controls="flush-collapse3">
                    Разделы дисциплины
                </button>
            </h2>
            <div id="flush-collapse3" class="accordion-collapse collapse" aria-labelledby="three">
                <div class="accordion-body">
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.MainSections</pre></span>
                </div>
            </div>
        </div>
    </div>
</div>

<br />
@Html.ActionLink("На главную", "Index", "Lessons", null, new { @class = "btn btn-outline-dark" })

@Html.ActionLink("Изменить дисциплины", "Index", "Disciplines", null, new { @class = "btn btn-outline-dark" })


<hr />


<sub><i>Описание может быть не точным</i></sub>

WebAppAspNetMvcAutofac/Views/Lessons/Edit.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Lesson

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()
        
        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Lessons", null, new { @class = "btn btn-danger" })
    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Lessons/Index.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@using Common.Extensions
@model List<Lesson>

@{
    string controllerName = "Lessons";
}
<br>
<h1><b>Расписание</b></h1>

<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Номер пары
            </th>
            <th>
                Дисциплина
            </th>
            <th>
                Группа(ы)
            </th>
            <th>
                Преподаватель
            </th>
            <th>
                Фото преподавателя
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var lesson in Model)
        {
            <tr >
                <td >
                    @lesson.Number
                </td>
                <td>
                    <a href="/Lessons/Detail/@lesson.Id">@lesson.Discipline.Name</a>

                </td>
                <td>
                    @string.Join(", ", lesson.Groups.Select(x => $"{x.GroupName}"))
                </td>
                <td>
                    @lesson.Teacher.Name
                </td>
                <td>
                    <img src="/Teachers/GetImage/@lesson.TeacherId"class="rounded" style="max-width: 50px; max-height: 100px;" />
                </td>
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@lesson.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@lesson.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br>
<div class="btn-create" style="display: flex; justify-content: flex-end;">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })    
</div>
 
<br>
<br>
<br>
<br>
<br>
<hr>
<footer>
    <dl>
        <dt>Дополнительная информация:</dt>
    </dl>
    <ol type="I">
        <li><h6><i>Данная работа сделана в ознакомительных целях</i></h6></li>
        <li><h6><i>Все люди вымышлены, а совпадения случайны</i></h6></li>
    </ol>

</footer>

WebAppAspNetMvcAutofac/Views/Shared/EditorTemplates/Boolean.cshtml
@{
    bool? value = null;
    if (ViewData.Model != null)
    {
        value = Convert.ToBoolean(ViewData.Model, System.Globalization.CultureInfo.InvariantCulture);
    }
}

<div class="form-check">
    <input class="form-check-input" name="@ViewData.TemplateInfo.HtmlFieldPrefix" type="checkbox" value="@(value ?? false)" >
    <label class="form-check-label">
        @ViewData.ModelMetadata.DisplayName
    </label>
</div>

WebAppAspNetMvcAutofac/Views/Shared/EditorTemplates/DateTime.cshtml
@{
    Dictionary<string, object> attributes = new Dictionary<string, object>();
    attributes["class"] = "form-control";

    string res = string.Empty;

    if (ViewData.Model != null && (DateTime)ViewData.Model > DateTime.MinValue)
    {
        var local = (DateTime)ViewData.Model.ToLocalTime();
        res = local.ToString("dd.MM.yyyy");
    }
}
@Html.TextBox("", res, attributes)

WebAppAspNetMvcAutofac/Views/Shared/EditorTemplates/Decimal.cshtml
@functions{
    private object ModelValue
    {
        get
        {
            if (ViewData.TemplateInfo.FormattedModelValue == ViewData.ModelMetadata.Model)
            {
                return String.Format(System.Globalization.CultureInfo.CurrentCulture, "{0:0.00}", ViewData.ModelMetadata.Model);
            }
            return ViewData.TemplateInfo.FormattedModelValue;
        }
    }
}
@{
    Dictionary<string, object> attributes = new Dictionary<string, object>();
    attributes["class"] = "form-control";
    attributes["maxlength"] = "20";
    }
@Html.TextBox("", ModelValue, attributes)

WebAppAspNetMvcAutofac/Views/Shared/EditorTemplates/DropDownList.cshtml
@using Common.Attributes
@model IEnumerable<SelectListItem>

@{
    var targetProperty = this.ViewData.ModelMetadata.PropertyName;
    var targetPropertyAttribute = this.ViewData.ModelMetadata.ContainerType.GetProperty(this.ViewData.ModelMetadata.PropertyName).GetCustomAttributes(typeof(TargetPropertyAttribute), true);
    if (targetPropertyAttribute.Any())
    {
        targetProperty = ((TargetPropertyAttribute)targetPropertyAttribute.First()).TargetProperty;
    }
}
<select class="form-select" id="@targetProperty" name="@targetProperty" >
    @if (Model != null)
    {
        foreach (SelectListItem item in Model)
        {
            <option value="@item.Value" @(item.Selected ? "selected" : "") @(item.Disabled ? "disabled" : "")>@item.Text </option>
        }
    }
</select>

WebAppAspNetMvcAutofac/Views/Shared/EditorTemplates/HttpPostedFileBase.cshtml
@model HttpPostedFileBase

<input name="@ViewData.TemplateInfo.HtmlFieldPrefix" type="file" class="form-control"/>

WebAppAspNetMvcAutofac/Views/Shared/EditorTemplates/Int32.cshtml
@model System.Int32?
@{
    Dictionary<string, object> attributes = new Dictionary<string, object>();
    attributes["class"] = "form-control";
    attributes["maxlength"] = "10";
    }
@Html.TextBox("", (Model.HasValue) ? ViewData.TemplateInfo.FormattedModelValue : "", attributes)

WebAppAspNetMvcAutofac/Views/Teachers/Create.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Teacher

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Teachers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Teachers", null, new { @class = "btn btn-danger" })
    }
</fieldset>

WebAppAspNetMvcAutofac/Views/Teachers/Edit.cshtml
@using WebAppAspNetMvcAutofac.DataModel
@model Teacher

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Teachers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Teachers", null, new { @class = "btn btn-danger" })
    }
    
</fieldset>